spring.application.name=xamle
spring.profiles.active=local

# Base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/xamle_sante
spring.datasource.username=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html